[repository]
name = "hyprexpo-plus"
authors = ["sandwich.farm"]

[hyprexpo-plus]
description = "hyprexpo+ â€” keyboard selection, labels, gaps, and Hyprland-style borders"
authors = ["sandwich"]
output = "hyprexpo.so"
build = [
"make all"
]

since_hyprland = 6559